### PR TITLE
do client signout before the TTransport is closed

### LINKED ISSUE #101: do client signout before the TTransport is closed
code in GraphClientImpl#close() works like this
```
public void close() {
    super.close();
    try {
        client.signout(sessionID);
    } catch (TException e) {
        LOGGER.error("Disconnect error: " + e.getMessage());
    } finally {
        transport.close();
    }
}
```
we should do client#signout before super.close(), or Disconnect error: Cannot write to null outputStream will be occur

### PR DESCRIPTION
**Pull request by chenxu14**
fixes #101

### CODE REVIEW

File: client/src/main/java/com/vesoft/nebula/client/graph/GraphClientImpl.java [hunk 1]
```diff
@@ -141,13 +141,12 @@ public ResultSet executeQuery(String statement) throws ConnectionException,
      * Sign out from Graph Services.
      */
     public void close() {
-        super.close();
         try {
             client.signout(sessionID);
         } catch (TException e) {
             LOGGER.error("Disconnect error: " + e.getMessage());
         } finally {
-            transport.close();
```
Comment (darionyaphet) [inline client/src/main/java/com/vesoft/nebula/client/graph/GraphClientImpl.java:150]: maybe we should append `super.close()` after `transport.close()`

Comment (darionyaphet) [reply client/src/main/java/com/vesoft/nebula/client/graph/GraphClientImpl.java:150]: it seems ok. But we should keep the usage
